# -*- coding: utf-8 -*-
"""Nonce & Target Value

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PNJAJZVls88gnJZlReTuM8gSx54UaHW1
"""

import hashlib

# ------------------------------------------
# Simulated block data
# ------------------------------------------
block_data = "Alice pays Bob 5 BTC"
target_prefix = "0000"        # target: hash must start with 4 zeros

nonce = 0                     # starting nonce
max_tries = 200000            # safety limit

# ------------------------------------------
# Mining loop: try different nonces
# ------------------------------------------
while nonce < max_tries:
    # Build the block header (data + nonce)
    block_header = block_data + str(nonce)

    # Compute SHA-256 hash of the block header
    block_hash = hashlib.sha256(block_header.encode()).hexdigest()

    # Check if hash meets target requirement
    if block_hash.startswith(target_prefix):
        print("VALID HASH FOUND!")
        print(f"Nonce: {nonce}")
        print(f"Hash:  {block_hash}")
        break

    nonce += 1

else:
    print("No valid hash found within max_tries")

import hashlib

block_data = "Alice pays Bob 5 BTC"

print("Scanning 10,000 hashes for leading zeros...\n")

for nonce in range(10_000):
    header = block_data + str(nonce)
    h = hashlib.sha256(header.encode()).hexdigest()

    # 1 leading zero
    if h.startswith("0"):
        print(f"[1 zero ] Nonce: {nonce:5d} | Hash: {h}")

    # 2 leading zeros
    if h.startswith("00"):
        print(f"[2 zeros] Nonce: {nonce:5d} | Hash: {h}")

    # 3 leading zeros (rare but possible)
    if h.startswith("000"):
        print(f"[3 zeros] Nonce: {nonce:5d} | Hash: {h}  <-- RARE")