# -*- coding: utf-8 -*-
"""SHA-256 Unique Output

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ir3yJh1RLvbNtEXgLBHzYy-balmmc4Np
"""

import hashlib

inputs = [
    "Hello Blockchain",
    "2025",
    "Alice pays Bob 5 BTC"
]

for text in inputs:
    hash_output = hashlib.sha256(text.encode()).hexdigest()
    print(f"Input: {text}\nSHA-256: {hash_output}\n")